@baseURL = http://localhost:8080/api/v1/auth


### Register
POST {{baseURL}}/register
Content-Type: application/json

{
    "name": "pedro",
    "email": "test321@gmail.com",
    "password": "password123",
    "confirmPassword": "password123"
}

### Login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "test321@gmail.com",
    "password": "password123"
}

### Logout
POST {{baseURL}}/logout
Content-Type: application/json 


### Refresh
GET {{baseURL}}/refresh 


### Verify email 
POST {{baseURL}}/verify/email
Content-Type: application/json

{
    "code": "b0cc712557b64562bf6959473"
}


### Forgot Password 
POST {{baseURL}}/password/forgot
Content-Type: application/json

{
    "email": "test321@gmail.com"
}

### Reset Password 
POST {{baseURL}}/password/reset
Content-Type: application/json

{
    "password": "test@123",
    "verificationCode": "4c9043ad29ab4a5c9501b72c1"
}