import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { Providers } from "@/providers/providers";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background antialiased ${dm_sans.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
